#########################################################
#                    AGBETOGOR GERMAIN               OKAY
#########################################################
# Secret for accessing ECR registry
#########################################################
# Configurer .docker/config.json pour accéder aux registry
---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIiA6ICJkZXNrdG9wIiwKICAiZXhwZXJpbWVudGFsIiA6ICJkaXNhYmxlZCIsCiAgIkh0dHBIZWFkZXJzIiA6IHsKICAgICJVc2VyLUFnZW50IiA6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjEyIChkYXJ3aW4pIgogIH0sCiAgImF1dGhzIiA6IHsKICAgICIwOTc0NjQ5NDc2MDkuZGtyLmVjci5ldS13ZXN0LTMuYW1hem9uYXdzLmNvbSIgOiB7CgogICAgfQogIH0sCiAgInN0YWNrT3JjaGVzdHJhdG9yIiA6ICJzd2FybSIKfQo=
type: kubernetes.io/dockerconfigjson
---
#########################################################
# cinetpay_core_mpms deployment 
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinetpay-core-mccs  
spec:
  selector:
    matchLabels:
      app: cinetpay-core-mccs
  replicas: 1
  template:
    metadata:
      labels:
        app: cinetpay-core-mccs
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
      - name: cinetpay-core-mccs 
        image: 097464947609.dkr.ecr.eu-west-3.amazonaws.com/cinetpay_core_mccs:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      dnsPolicy: Default      
---
#########################################################
# cinetpay_composite_gic service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: cinetpay-core-mccs-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: cinetpay-core-mccs 