#########################################################
#                  OKOU MICHEL                      
#########################################################
# Secret for accessing ECR registry
#########################################################
# Configurer .docker/config.json pour accéder aux registry
---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIiA6ICJkZXNrdG9wIiwKICAiZXhwZXJpbWVudGFsIiA6ICJkaXNhYmxlZCIsCiAgIkh0dHBIZWFkZXJzIiA6IHsKICAgICJVc2VyLUFnZW50IiA6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjEyIChkYXJ3aW4pIgogIH0sCiAgImF1dGhzIiA6IHsKICAgICIwOTc0NjQ5NDc2MDkuZGtyLmVjci5ldS13ZXN0LTMuYW1hem9uYXdzLmNvbSIgOiB7CgogICAgfQogIH0sCiAgInN0YWNrT3JjaGVzdHJhdG9yIiA6ICJzd2FybSIKfQo=
type: kubernetes.io/dockerconfigjson
---
#########################################################
# cinetpay_flooz_tg deployment 
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinetpay-flooz-tg  
spec:
  selector:
    matchLabels:
      app: cinetpay-flooz-tg
  replicas: 1
  template:
    metadata:
      labels:
        app: cinetpay-flooz-tg
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
      - name: cinetpay-flooz-tg 
        image: 097464947609.dkr.ecr.eu-west-3.amazonaws.com/cinetpay_core_pps_flooztg:0.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      dnsPolicy: Default      
---
#########################################################
# cinetpay_omwebpayci service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: cinetpay-flooz-tg-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: cinetpay-flooz-tg